from __future__ import annotations

import hashlib
import io
import re
from typing import Any

import pandas as pd
import streamlit as st

from excel_utils import analyze_template_sheet, get_days_in_month, infer_month_year, parse_attendance_input
from identity import (
    STATUS_MISSING_ATTENDANCE,
    STATUS_NOT_PRESENT,
    STATUS_REGISTERED,
    STATUS_REGISTERED_NAME_VARIANT,
    STATUS_REVIEW,
    build_attendance_indexes,
    load_identity_register,
    normalize_employee_id,
    payroll_mapping_key,
    resolve_template_rows,
    validate_mapping_conflicts,
)
from payroll_engine import (
    detect_active_sheet_names,
    detect_template_month_safe,
    generate_payroll_workbook,
    load_workbook,
    sha256_bytes,
    validate_attendance_records,
)

st.set_page_config(
    page_title="Payroll Automator",
    page_icon="💸",
    layout="wide",
)

st.title("Payroll Automator")
st.caption(
    "Payroll template + attendance Excel produced by the ESSL Extractor. "
    "Two inputs only."
)

DEFAULTS = {
    "template_hash": None,
    "attendance_hash": None,
    "target_month": None,
    "attendance_records": [],
    "template_data": {},
    "template_month": None,
    "active_sheets": [],
    "mapping_state": {},
    "new_hires": [],
    "generated_file": None,
    "generated_filename": None,
}
for key, value in DEFAULTS.items():
    st.session_state.setdefault(key, value)


def reset_for_inputs(template_hash: str, attendance_hash: str):
    if (
        template_hash != st.session_state.template_hash
        or attendance_hash != st.session_state.attendance_hash
    ):
        st.session_state.template_hash = template_hash
        st.session_state.attendance_hash = attendance_hash
        st.session_state.mapping_state = {}
        st.session_state.new_hires = []
        st.session_state.generated_file = None
        st.session_state.generated_filename = None


def format_days(value: Any) -> str:
    try:
        value = float(value or 0)
    except Exception:
        return "0"
    return str(int(value)) if value.is_integer() else f"{value:.2f}"


with st.sidebar:
    st.markdown("### Payroll Configuration")
    template_file = st.file_uploader(
        "1. Payroll template",
        type=["xlsx"],
        key="template_file",
    )
    attendance_file = st.file_uploader(
        "2. Attendance output from ESSL Extractor",
        type=["xlsx", "xls"],
        key="attendance_file",
        help="Use the attendance Excel generated by the ESSL Extractor. It contains Payroll Present Days calculated from the daily ESSL grid and payroll holiday/weekend rules.",
    )
    archive_enabled = st.checkbox(
        "Archive previous month's consultants",
        value=True,
    )

if template_file is None or attendance_file is None:
    st.info("Upload the payroll template and the attendance Excel to begin.")
    st.stop()

template_hash = sha256_bytes(template_file)
attendance_hash = sha256_bytes(attendance_file)
reset_for_inputs(template_hash, attendance_hash)

try:
    month_from_attendance, attendance_records = parse_attendance_input(
        attendance_file,
        filename=attendance_file.name,
    )
except Exception as exc:
    st.error(f"Could not read attendance workbook: {exc}")
    st.stop()

issues = validate_attendance_records(attendance_records)
if issues:
    st.error("Attendance validation failed:")
    for issue in issues[:20]:
        st.write(f"• {issue}")
    st.stop()

st.session_state.attendance_records = attendance_records

try:
    template_wb = load_workbook(template_file)
    template_month = detect_template_month_safe(template_wb)
    active_sheets = detect_active_sheet_names(template_wb, template_month)
    template_data = {
        sheet_name: analyze_template_sheet(template_wb[sheet_name])
        for sheet_name in active_sheets
    }
    identity_register = load_identity_register(template_wb)
    template_wb.close()
except Exception as exc:
    st.error(f"Could not inspect payroll template: {exc}")
    st.stop()

st.session_state.template_month = template_month
st.session_state.active_sheets = active_sheets
st.session_state.template_data = template_data

default_month = (
    st.session_state.target_month
    or month_from_attendance
    or template_month
    or ""
)
st.session_state.target_month = st.text_input(
    "Target Payroll Month & Year",
    value=default_month,
)

total_days = get_days_in_month(st.session_state.target_month)

st.markdown("### Run Summary")
c1, c2, c3, c4 = st.columns(4)
c1.metric("Attendance Records", len(attendance_records))
c2.metric("Active Payroll Sheets", len(active_sheets))
c3.metric(
    "Payroll Rows",
    sum(
        len(section.get("rows", []))
        for sections in template_data.values()
        for section in sections
    ),
)
c4.metric("Days in Month", total_days)

payroll_days_available = sum(
    1 for record in attendance_records if record.get("payroll_present_days") is not None
)
st.caption(
    f"Attendance records with Payroll Present Days: {payroll_days_available} / {len(attendance_records)}"
)

if not st.session_state.mapping_state:
    st.session_state.mapping_state = {
        m["mapping_key"]: m
        for m in resolve_template_rows(
            template_data,
            attendance_records,
            identity_register,
        )
    }

mappings = st.session_state.mapping_state
attendance_by_id, _ = build_attendance_indexes(attendance_records)
attendance_options = [
    normalize_employee_id(r.get("employee_id"))
    for r in attendance_records
    if normalize_employee_id(r.get("employee_id"))
]
attendance_labels = {
    normalize_employee_id(r.get("employee_id")):
        f"{normalize_employee_id(r.get('employee_id'))} | {r.get('name')} | "
        f"{format_days(r.get('days_present'))} payable days"
    for r in attendance_records
    if normalize_employee_id(r.get("employee_id"))
}

conflicts = validate_mapping_conflicts(list(mappings.values()))
review_count = sum(
    1 for m in mappings.values()
    if m.get("needs_confirmation") and not m.get("confirmed")
)
id_match_count = sum(
    1 for m in mappings.values()
    if m.get("confirmed")
    and m.get("essl_id")
    and m.get("status") in {
        STATUS_REGISTERED,
        STATUS_REGISTERED_NAME_VARIANT,
        "USER CONFIRMED",
        "EXACT NAME MATCH",
    }
)
no_attendance_count = sum(
    1 for m in mappings.values()
    if m.get("status") in {
        STATUS_NOT_PRESENT,
        STATUS_MISSING_ATTENDANCE,
    }
)

mc1, mc2, mc3, mc4 = st.columns(4)
mc1.metric("ID / Exact Matched", id_match_count)
mc2.metric("Needs Review", review_count)
mc3.metric("No Attendance", no_attendance_count)
mc4.metric("ID Conflicts", len(conflicts))

if conflicts:
    st.error("The same ESSL Employee ID is assigned to more than one payroll row.")

tab1, tab2, tab3 = st.tabs(
    ["Identity & Attendance", "Payroll Preview", "Generate"]
)

with tab1:
    st.subheader("Identity Mapping")

    if identity_register:
        st.success(
            f"Persistent identity register found: {len(identity_register)} mapping(s)."
        )
    else:
        st.info(
            "First run: exact names are matched automatically. "
            "Name variants require confirmation."
        )

    for sheet_name, sections in template_data.items():
        st.markdown(f"#### {sheet_name}")
        for section in sections:
            st.markdown(f"**{section['type'].capitalize()}**")
            for emp in section.get("rows", []):
                key = payroll_mapping_key(
                    sheet_name,
                    section["type"],
                    int(emp["row_num"]),
                )
                mapping = mappings[key]
                status = mapping.get("status")
                current_id = normalize_employee_id(mapping.get("essl_id"))

                cols = st.columns([2.4, 2.4, 1.0, 1.5])
                cols[0].markdown(
                    f"**{mapping.get('payroll_name')}**\n\n"
                    f"{sheet_name} · row {emp['row_num']}"
                )
                cols[1].markdown(
                    f"Payroll code: `{mapping.get('payroll_code') or 'N/A'}`\n\n"
                    f"ESSL ID: `{current_id or 'None'}`"
                )
                cols[2].markdown(
                    f"**{format_days(mapping.get('days_present'))}** payable days"
                )

                if mapping.get("needs_confirmation"):
                    cols[3].warning(status or "REVIEW")
                    values = ["__NONE__"] + attendance_options
                    labels = {"__NONE__": "Select attendance identity"}
                    labels.update(attendance_labels)

                    selected = st.selectbox(
                        "Attendance identity",
                        values,
                        index=(
                            values.index(current_id)
                            if current_id in values
                            else 0
                        ),
                        format_func=lambda value: labels.get(value, value),
                        key=f"map_select_{key}",
                    )

                    if selected != "__NONE__":
                        if selected != current_id:
                            rec = attendance_by_id[selected]
                            mapping["essl_id"] = selected
                            mapping["attendance_name"] = rec.get("name", "")
                            mapping["days_present"] = float(
                                rec.get("days_present") or 0
                            )
                            mapping["payroll_present_days"] = float(
                                rec.get("payroll_present_days")
                                or rec.get("days_present")
                                or 0
                            )
                            mapping["confirmed"] = False
                            mapping["needs_confirmation"] = True
                            mapping["status"] = STATUS_REVIEW
                            mapping["match_method"] = "user_selected"
                            mapping["note"] = (
                                "Attendance identity selected by user. "
                                "Confirmation required."
                            )
                            st.rerun()

                        confirmed = st.checkbox(
                            "Confirm identity",
                            value=bool(mapping.get("confirmed")),
                            key=f"confirm_{key}",
                        )
                        mapping["confirmed"] = confirmed
                        mapping["needs_confirmation"] = not confirmed

                        if confirmed:
                            mapping["status"] = "USER CONFIRMED"
                            mapping["match_method"] = "user_confirmed"
                            mapping["note"] = "Identity explicitly confirmed by user."
                else:
                    if status in {
                        STATUS_REGISTERED,
                        STATUS_REGISTERED_NAME_VARIANT,
                        "EXACT NAME MATCH",
                        "USER CONFIRMED",
                    }:
                        cols[3].success(status)
                    elif status == STATUS_MISSING_ATTENDANCE:
                        cols[3].info("Missing this month")
                    else:
                        cols[3].info(status or "Not present")

                if mapping.get("attendance_name"):
                    st.caption(
                        f"Attendance: {mapping['attendance_name']} | "
                        f"ESSL ID: {mapping.get('essl_id')} | "
                        f"Payable Days: {format_days(mapping.get('days_present'))}"
                    )
                if mapping.get("note"):
                    st.caption(mapping["note"])
                st.markdown("---")

with tab2:
    st.subheader("Payroll Preview")
    preview_rows = []

    for mapping in mappings.values():
        confirmed = bool(mapping.get("confirmed") and mapping.get("essl_id"))
        days = float(mapping.get("days_present") or 0) if confirmed else 0.0
        gross = float(mapping.get("gross_salary") or 0)

        prorated = gross * days / total_days if total_days else 0

        if mapping.get("section_type") == "employee":
            deduction = 200.0
            kind = "Employee"
        else:
            deduction = prorated * 0.10
            kind = "Freelancer (TDS)"

        preview_rows.append(
            {
                "Sheet": mapping.get("sheet_name"),
                "Type": kind,
                "Name": mapping.get("payroll_name"),
                "ESSL ID": mapping.get("essl_id", ""),
                "Payable Days": days,
                "Gross Base": gross,
                "Pro-rated Gross": round(prorated, 2),
                "TDS / Prof Tax": round(deduction, 2),
                "Net Salary": round(prorated - deduction, 2),
            }
        )

    if preview_rows:
        st.dataframe(
            pd.DataFrame(preview_rows),
            use_container_width=True,
            hide_index=True,
        )

with tab3:
    st.subheader("Generate Monthly Payroll")

    unresolved = [
        m for m in mappings.values()
        if m.get("needs_confirmation") and not m.get("confirmed")
    ]

    if unresolved:
        st.warning(
            f"{len(unresolved)} identity review(s) still require confirmation."
        )

    if conflicts:
        st.error("Generation is blocked because of duplicate confirmed ESSL IDs.")

    can_generate = not conflicts

    if st.button(
        "Generate Payroll Excel",
        type="primary",
        disabled=not can_generate,
    ):
        with st.spinner("Generating payroll workbook..."):
            try:
                generated, audit_rows, active = generate_payroll_workbook(
                    template_source=template_file,
                    attendance_source=attendance_file,
                    target_month=st.session_state.target_month,
                    mappings_by_key=mappings,
                    new_hires=st.session_state.new_hires,
                    archive_enabled=archive_enabled,
                )
                safe_month = re.sub(
                    r"[^A-Za-z0-9]+",
                    "_",
                    st.session_state.target_month,
                ).strip("_")
                st.session_state.generated_file = generated
                st.session_state.generated_filename = (
                    f"Payroll_{safe_month}.xlsx"
                )
                st.success(
                    f"Payroll generated successfully for {st.session_state.target_month}."
                )
                st.info(
                    f"Processed active sheets: {', '.join(active)}"
                )
            except Exception as exc:
                st.error(f"Payroll generation failed: {exc}")

if st.session_state.generated_file:
    st.download_button(
        "Download Generated Payroll Excel",
        data=st.session_state.generated_file,
        file_name=st.session_state.generated_filename or "Payroll_Output.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )
